version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-0869
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ticketsampleapplication7885_0869-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-0869
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-0869
    container_name: authproxy-0869
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-0869
    container_name: securitymanager-0869
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-0869
    container_name: camundasvc-0869
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-0869
    container_name: apigateway-0869
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - ticketsample
      - typessample
      - severitysample



  ticketsample: 
    build: ../../../application/services/custom_services/ticketsample
    image: ticketsample-0869
    container_name: ticketsample-0869
    ports: 
      - 8014:8014
    env_file: .env
    depends_on:
      - mongo

  typessample: 
    build: ../../../application/services/custom_services/typessample
    image: typessample-0869
    container_name: typessample-0869
    ports: 
      - 8015:8015
    env_file: .env
    depends_on:
      - mongo

  severitysample: 
    build: ../../../application/services/custom_services/severitysample
    image: severitysample-0869
    container_name: severitysample-0869
    ports: 
      - 8016:8016
    env_file: .env
    depends_on:
      - mongo


volumes:
  ticketsampleapplication7885_0869-volume:
    driver: local
